### ISSUE TITLE
A description of the models

### ISSUE THREAD

**Issue by xaionaro** [aleju/cat-generator#4]

**Comment by xaionaro** [comment]
Will not bother the author with my newbie questions. Closing/Canceling.

**Comment by aleju** [comment]
:)
I guess the lines that you had quoted were from the start of the generator. Then `128 * 4 * 4` denotes an initial height and width of 4. `128` is the initial number of channels, which is progressively reduced to 3 (RGB channels) throughout the layers. How many channels to pick is up to experimentation, there is no "correct" number. I don't remember why it was reduced compared to the readme. My best guess would be, that it was for faster performance during testing and then forgotten to increase again. `128` is on the low side for the initial channels number. Nowadays, 1024 would be more standard.

And where to place PReLU is also up to experimentation. Placing it before the `View` means that it should have `128 * 4 * 4` weights (the slope of the activations), one for each neuron. Placing it behind the `View` should result in `128` weights, one for each channel. Having a single weight for all neurons of the same channel introduces a prior that these neurons somehow belong to each other and that *might* improve results or it *might* increase training speed (it might also do neither of these things).

**Comment by xaionaro** [comment]
Thank you a lot! :)
